SCM-NV/nano-qmflows

- README.rst
- test/utilsTest.py
Using a decorator to remove test files
> remove try_to_remove duplicate function

- .travis.yml
- nac/integrals/nonAdiabaticCoupling.py
- test/benchmark_coupling.py
Added optimization on the calculation of the couplings to the master branch.
> Optimization

- nac/integrals/nonAdiabaticCoupling.py
Reduce the memory usage by creating a lower number of intermediate numpy arrays
> reduce memory footprint

- nac/integrals/nonAdiabaticCoupling.py
- nac/schedule/scheduleCoupling.py
Compute first the Atomic overlap matrices and then read from the HDF5 the Molecular Orbitals to reduce the impact of memory of loading everything beforehand.
> Read the MOs after the Overlap has been computed

- nac/schedule/components.py
Fixed issue when restarting a calculation using the OT
> fixed computation of the guess OT with Cp2k

- nac/workflows/workflow_coupling.py
Speed the reading of the overlap matrix
> change the order of the schedule functions

- nac/workflows/workflow_cube.py
fixed memory problem with noodles
> move the loop for the geometries inside one node of the workflow

- .travis.yml
- CHANGELOG.md
- LICENSE
- setup.py
- test/test_coupling.py
Speed up the code and reduce the memory fingerprint
> cleanup the code

- .gitignore
- .travis.yml
- nac/integrals/nonAdiabaticCoupling.py
- nac/schedule/scheduleCoupling.py
- nac/workflows/input_validation.py
- nac/workflows/schemas.py
- nac/workflows/workflow_coupling.py
> renamed couplings_range to mo_index_range

- .travis.yml
- test/test_files/input_test_absorption_spectrum.yml
> fixed #123

- nac/workflows/input_validation.py
- nac/workflows/schemas.py
- scripts/distribution/distribute_jobs.py
- test/test_distribute.py
- test/test_files/input_fast_test_derivative_couplings.yml
- test/test_files/input_test_absorption_spectrum.yml
- test/test_files/input_test_derivative_couplings.yml
- test/test_files/input_test_distribute_absorption_spectrum.yml
- test/test_files/input_test_pbe.yml
- test/test_files/input_test_pbe0.yml
> made distribute also available with absorption spectrum

- nac/__init__.py
fixed issue importing analysis tools
> added analysis function to __init__

- libint/compute_integrals.cc
> compute multipole at the center of mass

- nac/workflows/input_validation.py
- nac/workflows/schemas.py
- test/test_files/file_cell_parameters.txt
- test/test_files/input_test_pbe.yml
- test/test_files/input_test_pbe0.yml
> created array of cell parameters to pass to qmflows

- nac/workflows/input_validation.py
- test/test_input_validation.py
> returned a input_parameters.yml file after the preprocessing #149

- CHANGELOG.md
- nac/schedule/scheduleCoupling.py
- nac/workflows/workflow_stddft_spectrum.py
- setup.py
> fixed #156

- nac/workflows/schemas.py
> fixed #155

- nac/workflows/__init__.py
- nac/workflows/input_validation.py
- nac/workflows/schemas.py
- nac/workflows/workflow_single_points.py
- scripts/cli/run_workflow.py
- scripts/distribution/distribute_jobs.py
- test/test_files/input_test_single_points.yml
- test/test_input_validation.py
- test/test_worflow_single_points.py
- test/utilsTest.py
> solved #157

- nac/workflows/workflow_stddft_spectrum.py
- test/test_absorption_spectrum.py
- test/test_worflow_single_points.py
- test/utilsTest.py
> fixed #164

- nac/__init__.py
- nac/analysis/__init__.py
- nac/analysis/tools.py
- nac/workflows/schemas.py
> removed unused rdf #168

- .travis.yml
- nac/workflows/workflow_stddft_spectrum.py
> fixed #170

- .travis.yml
- nac/workflows/workflow_stddft_spectrum.py
- scripts/distribution/distribute_jobs.py
> fixed #171

- nac/workflows/initialization.py
- scripts/distribution/distribute_jobs.py
- test/test_files/input_test_distribute_absorption_spectrum.yml
> fixed #186

- libint/compute_integrals.cc
- nac/schedule/components.py
- nac/workflows/workflow_coupling.py
- nac/workflows/workflow_single_points.py
- nac/workflows/workflow_stddft_spectrum.py
- test/test_coupling.py
- test/test_worflow_single_points.py
> solved #184

- nac/workflows/input_validation.py
- nac/workflows/schemas.py
> fixed #190

- nac/integrals/nonAdiabaticCoupling.py
- nac/schedule/scheduleCoupling.py
- nac/workflows/input_validation.py
> fixed #196

- nac/integrals/nonAdiabaticCoupling.py
- nac/workflows/workflow_coupling.py
> fix levine

- nac/integrals/nonAdiabaticCoupling.py
> fixed isue with sinc function in levine #199

- nac/schedule/components.py
- nac/workflows/input_validation.py
- nac/workflows/schemas.py
- nac/workflows/workflow_single_points.py
- test/test_files/input_test_single_points.yml
- test/test_worflow_single_points.py
> Optionally compute and store the orbitals for the single point workflow

- nac/schedule/components.py
- nac/schedule/scheduleCp2k.py
- nac/workflows/input_validation.py
- nac/workflows/schemas.py
- nac/workflows/workflow_stddft_spectrum.py
- scripts/distribution/distribute_jobs.py
- setup.py
- test/test_absorption_spectrum.py
- test/test_coupling.py
- test/test_cp2k_executable.py
- test/test_distribute.py
- test/test_files/input_fast_test_derivative_couplings.yml
- test/test_files/input_test_IPR.yml
- test/test_files/input_test_absorption_spectrum.yml
- test/test_files/input_test_coop.yml
- test/test_files/input_test_distribute_absorption_spectrum.yml
- test/test_files/input_test_distribute_derivative_couplings.yml
- test/test_files/input_test_pbe.yml
- test/test_files/input_test_pbe0.yml
- test/test_files/input_test_single_points.yml
- test/test_tools.py
- test/test_workflow_IPR.py
- test/test_workflow_coop.py
> Allow for more cp2k executables

- nac/workflows/input_validation.py
- scripts/distribution/distribute_jobs.py
- test/test_distribute.py
> Remove Settings2Dict

- .github/workflows/pythonapp.yml
- .travis.yml
- README.rst
- libint/compute_integrals.cc
- libint/include/namd.hpp
Use [libint 2.6.0](https://github.com/evaleev/libint)
> Use a newer version of libint

- docs/conf.py
- docs/cp2k_interface.rst
- docs/derivative_coupling.rst
- docs/documentation.rst
- docs/index.rst
- docs/integrals.rst
- docs/molecular_orbitals.rst
- docs/workflows.rst
- nac/integrals/nonAdiabaticCoupling.py
- nac/schedule/__init__.py
- nac/schedule/components.py
- nac/schedule/scheduleCP2K.py
- nac/workflows/workflow_coop.py
- nac/workflows/workflow_coupling.py
> Improve some docs

- CHANGELOG.md
- docs/command_line.rst
- docs/documentation.rst
- nac/workflows/distribute_jobs.py
- nac/workflows/run_workflow.py
- nac/workflows/schemas.py
- setup.py
- test/test_files/input_test_distribute_derivative_couplings.yml
Added the `free_format` entry in the YAML input file that allows the user to specify the SLURM commands in a free format.
solved #225
> Allow slurm free format options

- nanoqm/workflows/input_validation.py
- test/utilsTest.py
Directly add the ``eigenvalues`` and ``eigenvectors`` coefficients to print the molecular orbitals.
> Print CP2K MO

- .github/workflows/pythonapp.yml
- CHANGELOG.md
- nanoqm/workflows/distribute_jobs.py
- test/test_files/input_test_distribute_derivative_couplings.yml
Remove empty spaces at the beginning of the SLURM free-format specification #245
> Free Slurm free format

- CHANGELOG.md
- nanoqm/workflows/initialization.py
Touch HDF5 if it doesn't exist at the workflow start
> fixed #246

- CHANGELOG.md
- nanoqm/common.py
- nanoqm/workflows/distribute_jobs.py
Solved #247 by creating a separated `scratch` folder for each chunk.
> Create a scratch folder for each distributed chunk

- nanoqm/workflows/distribute_jobs.py
Fix typo when writing distributing calculations #245
> fix typo in distribution

- nanoqm/schedule/scheduleCP2K.py
- nanoqm/workflows/input_validation.py
fix small f-string typo and comment
> fix f-string typo

- nanoqm/schedule/scheduleCP2K.py
Do not check if the CP2K calculation contains the OT keyword
> Multivalue

- nanoqm/workflows/input_validation.py
- nanoqm/workflows/schemas.py
- test/test_cp2k_executable.py
- test/test_files/input_test_pbe.yml
- test/test_files/input_test_single_points.yml
- test/utilsTest.py
> set CP2K path correctly

- CHANGELOG.md
- nanoqm/workflows/distribute_jobs.py
- nanoqm/workflows/initialization.py
- test/test_distribute.py
> solved enumerate_from issue

- nanoqm/common.py
- nanoqm/schedule/components.py
- nanoqm/schedule/scheduleCoupling.py
- nanoqm/workflows/input_validation.py
- nanoqm/workflows/schemas.py
- nanoqm/workflows/workflow_coupling.py
- test/test_files/input_test_single_points.yml
> Compute derivative couplings for system with multiplicity different of 1

- nanoqm/workflows/workflow_coupling.py
Previously one workflow was invoke after the other using the same `cache.db` file, causing problems to restart.
> fix #283 by running alphas and betas in same workflow

- nanoqm/workflows/distribute_jobs.py
Fix Hamiltonian paths for unrestricted calculations
> solved #286

- CHANGELOG.md
- nanoqm/schedule/scheduleCoupling.py
> solved issue #290

- CHANGELOG.md
- nanoqm/workflows/schemas.py
solved #292 by using the [Regex numeric flag for IGNORECASE](https://docs.python.org/3/howto/regex.html#compilation-flags) instead of `re.I`
see [schema#246](https://github.com/keleshev/schema/issues/246)
> Use regex numeric flag

- CHANGELOG.md
- nanoqm/workflows/distribute_jobs.py
Solved #296 by properly counting the number of Hamiltonian files to retrieve
> fix slurm launch script

- test/test_cli.py
Add a test for the `run_workflow.py` script
> Add more tests

- .github/workflows/build.yml
- .github/workflows/pythonapp.yml
- CHANGELOG.md
- scripts/qmflows/removeHDF5folders.py
- test/test_workflow_single_points.py
> fix bug removing HDF5 groups

- scripts/qmflows/removeHDF5folders.py
bug reading the path to the HDF5 in the `removeHDF5folders.py` script
> Fix removeHDF5folders script

- CHANGELOG.md
- nanoqm/schedule/components.py
Fix #324 by allowing to load different geometries.
> solve #324

- nanoqm/common.py
- nanoqm/workflows/distribute_jobs.py
- nanoqm/workflows/input_validation.py
- nanoqm/workflows/run_workflow.py
- nanoqm/workflows/templates.py
- test/test_cli.py
- test/test_initialization.py
Closes https://github.com/SCM-NV/nano-qmflows/issues/308.
Use the new yaml loaders that raise upon encountering duplicate keys.
> ENH: Use the new qmflows `UniqueSafeLoader` for loading .yaml files

- nanoqm/workflows/input_validation.py
- nanoqm/workflows/schemas.py
- nanoqm/workflows/templates.py
- test/test_input_validation.py
> ENH: Add settings for manual choice of XC functionals for GGA, MGGA and hybrids

- .github/workflows/pythonapp.yml
- setup.py
- test_requirements.txt
Allows for automatic installation of the new noodles 0.3.4 release.
> BLD: Remove the upper version bound of noodles

- .github/workflows/pythonapp.yml
- CHANGELOG.md
- nanoqm/__version__.py
- pyproject.toml
- setup.py
Prepare for the 0.12.3 release and revert https://github.com/SCM-NV/nano-qmflows/commit/3903b1ad4891b13caa8107b57aeaa873c318fe0d (for now) as https://github.com/SCM-NV/nano-qmflows/pull/360 proves to be more difficult than anticipated.
> REL: Prepare for Nano-QMFlows 0.12.3

- .github/workflows/pypi.yaml
- .github/workflows/pythonapp.yml
- README.rst
- conftest.py
- install_requirements.txt
- libint/compute_integrals.cc
- libint/include/namd.hpp
- nanoqm/schedule/components.py
- pyproject.toml
- scripts/prepare_test_dir.sh
- test/test_citation_cff.py
- test/test_version.py
Adds some new tests and performs a bit of general maintenance.
> TST: Add tests for CITATION.cff and __version__

- .github/workflows/pypi.yaml
- .github/workflows/pythonapp.yml
- CHANGELOG.md
- pyproject.toml
- setup.py
Build wheels that are compatible with the newer Apple silicon-based hardware.
> CI: Cross-compile macos_arm64 wheels
